# Generated by Django 5.0.2 on 2024-02-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='is_publushed',
            new_name='is_published',
        ),
    ]
