# Generated by Django 5.0.2 on 2024-02-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_is_publushed_aboutme_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginreg',
            options={'ordering': ['pk', 'menu_item'], 'verbose_name': 'LogRegМеню', 'verbose_name_plural': 'LogRegМеню'},
        ),
    ]
