"""
Django settings for me_website project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print('BASE_DIR>>>>>>>>>>>>>>>>>>>>>>>>>>>>>', BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8)twy6scuy=c%6w9(!7o+#cmx(2nvu@7mp5z$o#3hradtly5-$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '0.0.0.0', 'testserver', 'localhost']

CSRF_TRUSTED_ORIGINS = ['https://685a-178-121-28-214.ngrok-free.app']
# Application definition

INSTALLED_APPS = [
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # 'debug_toolbar',
    'channels',
    'main',
    # 'notes',
    'chat',
    'main_chat',
]

SITE_ID = 1

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'me_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = "me_website.asgi.application"
WSGI_APPLICATION = 'me_website.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [
    BASE_DIR / "static/",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = 'media/'

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'login'

INTERNAL_IPS = [
    '127.0.0.1'
]

# EMAIL_MAIL_TOKEN_LIFE = 60 * 5



# #
# #
# """
# Django settings for me_website project.
#
# Generated by 'django-admin startproject' using Django 4.1.2.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/4.1/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.1/ref/settings/
# """
# import os
# from pathlib import Path
#
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
#
# print('BASE_DIR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>', BASE_DIR)
#
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-8)twy6scuy=c%6w9(!7o+#cmx(2nvu@7mp5z$o#3hradtly5-$'
#
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
#
# ALLOWED_HOSTS = ['atrudoffcard.ru', 'www.atrudoffcard.ru', 'http://atrudoffcard.ru', 'https://www.atrudoffcard.ru']
#
# # CSRF_TRUSTED_ORIGINS = ['https://0b86-178-121-7-59.ngrok.io']
# # Application definition
#
# INSTALLED_APPS = [
#     'daphne',

#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'django.contrib.sites',
#     # 'debug_toolbar',
#     'channels',
#     'main',
#     'notes',
#     'chat',
#     'chat_main',
# ]
#
# SITE_ID = 2
#
# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     # 'debug_toolbar.middleware.DebugToolbarMiddleware',
# ]
#
# ROOT_URLCONF = 'me_website.urls'
#
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates']
#         ,
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
#
# ASGI_APPLICATION = "me_website.asgi.application"
# WSGI_APPLICATION = 'me_website.wsgi.application'
#
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer',
#     },
# }
#
#
# # Database
# # https://docs.djangoproject.com/en/4.1/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
#
#
# # Password validation
# # https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
#
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]
#
#
# # Internationalization
# # https://docs.djangoproject.com/en/4.1/topics/i18n/
#
# LANGUAGE_CODE = 'ru'
#
# TIME_ZONE = 'UTC'
#
# USE_I18N = True
#
# USE_TZ = True
#
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/4.1/howto/static-files/
#
# # STATIC_URL = 'static/'
# # STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#
# # STATICFILES_DIRS = [
# #     BASE_DIR / "static/",
# # ]
#
# # Default primary key field type
# # https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
#
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#
# # MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# # MEDIA_URL = 'media/'
#
# STATIC_URL = '/static/'
# MEDIA_URL = '/media/'
# STATICFILES_DIRS=[str(BASE_DIR) + "/assets",]
# MEDIA_ROOT = '/home/atrudoff/me_website/media'
# STATIC_ROOT ='/home/atrudoff/me_website/static'
#
# LOGIN_REDIRECT_URL = '/'
# LOGIN_URL = 'login'
#
# INTERNAL_IPS = [
#     '127.0.0.1'
# ]
#
# DEFAULT_FROM_EMAIL = 'hello@atrudoffcard.ru'
# SERVER_EMAIL = 'hello@atrudoffcard.ru'
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'mail.atrudoffcard.ru'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'hello@atrudoffcard.ru'
# EMAIL_HOST_PASSWORD = '10011978Alex'
# # EMAIL_MAIL_TOKEN_LIFE = 60 * 5
